### ISSUE TITLE
Typo when /leave

### ISSUE THREAD

**Issue by Olgabrezel** [GreyWolfDev/Coup#13]
When you /leave a game, it shows:

"You have been remove from game XXX"

It should be removeD, shouldn't it?

**Comment by CloneMMDDCVII** [comment]
@Olgabrezel Please do not make pull requests or open issues for language. As much as we aalreciate your dedication to the bot, it would really help us if you reported minor typos and bugs in t.me/werewolfsupport instead of opening issues here ;)
