### ISSUE TITLE
Bug in Concede

### ISSUE THREAD

**Issue by joshkurien** [GreyWolfDev/Coup#15]
In the middle of one's act, if one selects concede; the 4 inline buttons (Game status, concede, show cards and graveyard) disappear and is instead replaced by plain text string `Accepted`

Also, the game continues as it would (player is still in game) but this time  with the handicap of not being able to see the game status, graveyard or own cards

**Comment by joshkurien** [comment]
The message at 4:05

![852116954_4919066851493118382](https://cloud.githubusercontent.com/assets/7813196/21651233/de926d5c-d2cd-11e6-9708-6fe58985b7f6.jpg)

**Comment by parabola949** [comment]
This _should_ be fixed...  I think? I made it so you can only concede on your own turn
