### ISSUE TITLE
Unnecessary Allow-button

### ISSUE THREAD

**Issue by Olgabrezel** [GreyWolfDev/Coup#2]
I think, the allow button is unnecessary, because

1) if you use it, you get an interrupting pop-up
2) it is never used by all players

About 1): See my issue about that. The pop-up can also not be left out, because if allow-button exists, you have to somehow know it worked.

About 2): If a player chooses an action and noone calls / blocks it, I almost never see that he can do this action sofortly, which means, there is minimum 1 player who didn't hit allow. To go on with the action, everyone has to allow, or time for block/call has to run out. Because time almost always runs out, the physical presence of the button is not needed. And because of the disturbing pop-up, I think, this button should be removed completely.

**Comment by parabola949** [comment]
I am not removing the button.  In games where people do actually click it like they should, it is effective and moves the game along.  In games where people don't, it doesn't hurt anything.  As for the pop-up, yes, seriously, I get it as it has been mentioned MANY times.  Please chill, I already said I was going to fix that
